# HTTP MCP Server Configuration
quarkus.http.host=0.0.0.0
quarkus.http.port=${PORT:8080}
quarkus.http.cors.enabled=true
quarkus.mcp.server.http.root-path=/mcp

# Logging configuration
quarkus.log.level=INFO

# Lichess API configuration
lichess.api.token=
